spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://wwww.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://new.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedHeader: "*"
#            allowedMethods: "*"
#            addAllowedOriginPattern: "*"
#            allowCredentials: true
#        add-to-simple-url-handler-mapping: true
    nacos:
      discovery:
        server-addr: 1.116.28.38:8848
  application:
    name: mall-gateway