#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://wwww.baidu.com
#          predicates:
#            - Query=url,baidu
#        - id: qq_route
#          uri: https://new.qq.com
#          predicates:
#            - Query=url,qq
#        - id: product_route
#          uri: lb://mall-product
#          predicates:
#            - Path=/api/product/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /$\{segment}
#        - id: thirdparty_route
#          uri: lb://mall-third-party
#          predicates:
#            - Path=/api/thirdParty/**
#          filters:
#            - RewritePath=/api/thirdParty/?(?<segment>.*), /$\{segment}
#        - id: admin_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
#    nacos:
#      discovery:
#        server-addr: 1.116.28.38:8848
#  application:
#    name: mall-gateway