spring:
  cloud:
    nacos:
      discovery:
        server-addr: 1.116.28.38:8848
    alicloud:
      access-key: LTAI5t6LSqKr94C2ZzXpLzmR
      secret-key: HVAAWtF0zpZFN7Trasj2OV2BbL6pst
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: mall-morro
  application:
    name: mall-third-party

server:
  port: 30000